# Site settings
title: Madalin dot me
email: contact@madalin.me
description: > # this means to ignore newlines until "baseurl:"
  Ramblings by Madalin, a passionate Web Developer, possibly living on Mars.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://madalinignisca.github.io" # the base hostname & protocol for your site
twitter_username: 16nsk
github_username:  madalinignisca
company: They would ... me if I disclose the name.
permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: true

theme: minima

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
