# Site settings
title: Madalin Ignisca
email: madalin.ignisca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings by Madalin Ignisca -- a Romanian passionate Front end developer. Lives and works in UK.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabe.me.uk" # the base hostname & protocol for your site
twitter_username: 16nsk
github_username:  16nsk

# Build settings
markdown: kramdown
