# Site settings
title: Madalin dot me
email: hi@madalin.me
description: > # this means to ignore newlines until "baseurl:"
  Ramblings by Madalin, a passionate Web Developer, possibly living on Mars.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.madalin.me" # the base hostname & protocol for your site
twitter_username: 16nsk
github_username:  madalinignisca
company: MultiSafepay
permalink: ordinal
show_excerpts: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: true

theme: minima

disqus:
  shortname: gabb3

google_analytics: UA-65558242-3

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
